In [1]:
import numpy as np #importing the package

# 1. Create a 3x3x3 array with random values 

In [2]:
x = np.random.random((3,3,3))
print(x)

[[[0.73452903 0.13116317 0.44258454]
  [0.60729103 0.33381978 0.47987234]
  [0.03203844 0.37003095 0.95636176]]

 [[0.34266356 0.94989014 0.17632956]
  [0.84561876 0.15740137 0.39629414]
  [0.14243139 0.12686366 0.2794945 ]]

 [[0.60167931 0.39004028 0.08241745]
  [0.76572484 0.00250128 0.56485268]
  [0.55588606 0.94588984 0.68095045]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [32]:
print(np.diag(1+np.arange(4),k=-1))


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [14]:
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.72898132 0.8005636  0.76212528 0.6856496  0.82551039]
 [0.19535394 0.59654723 0.21168373 0.35693177 0.36389102]
 [0.99944681 0.04411065 0.92300569 0.06625308 0.31065612]
 [0.03927034 0.7779308  0.23809303 0.01506879 0.70521506]
 [0.28786573 0.03543034 0.0764107  0.77389835 0.27433038]]
After normalization:
[[0.72524225 0.79796054 0.7589122  0.68122286 0.82330323]
 [0.18314625 0.59070644 0.1997352  0.34728831 0.35435801]
 [1.         0.02950276 0.92234576 0.05199658 0.30027827]
 [0.02458563 0.77496855 0.22656362 0.         0.70109882]
 [0.2771262  0.02068468 0.0623154  0.77087211 0.26337605]]


# 5.  How to find common values between two arrays?

In [36]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
print("x=",x,"y=",y)
print("common values=",np.intersect1d(x,y))

x= [6 0 2 4 8 5 2 1 8 8] y= [7 5 8 0 3 1 1 8 0 1]
common values= [0 1 5 8]


# 6.How to get the dates of yesterday, today and tomorrow?

In [37]:
day = np.datetime64('today', 'D') 
print("Yestraday: ",day-np.timedelta64(1, 'D'))
print("Today: ",day)
print("Tomorrow: ",day+np.timedelta64(1, 'D'))

Yestraday:  2020-07-26
Today:  2020-07-27
Tomorrow:  2020-07-28


# 7. Consider two random array A and B, check if they are equal

In [53]:
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
equal = np.array_equal(x,y)
print(equal)

First array:
[1 0 0 1 1 1]
Second array:
[0 1 0 0 0 1]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [24]:
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

Original array:
[0.41360106 0.20785232 0.15650877 0.29743093 0.17375858 0.91600328
 0.35029373 0.74359508 0.4345768  0.97969063]
Maximum value replaced by 0:
[0.41360106 0.20785232 0.15650877 0.29743093 0.17375858 0.91600328
 0.35029373 0.74359508 0.4345768  0.        ]


# 9. How to print all the values of an array?

In [27]:
np.set_printoptions(threshold=np.nan)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 10.Subtract the mean of each row of a matrix

In [30]:
print("Original matrix:\n")
X = np.random.rand(3, 3)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.56059262 0.90563563 0.96558156]
 [0.41666002 0.37293682 0.70318293]
 [0.51027538 0.044367   0.664427  ]]

Subtract the mean of each row of the said matrix:

[[-0.25001065  0.09503236  0.15497829]
 [-0.08093324 -0.12465644  0.20558968]
 [ 0.10391892 -0.36198946  0.25807054]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [43]:
Z = np.ones(10)
print("Before")
print(Z)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print("After\n",Z)

Before
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
After
 [4. 4. 2. 1. 2. 2. 2. 3. 4. 6.]


# 12.How to get the diagonal of a dot product?

In [58]:
x = np.random.uniform(0,1,(3,3))
y = np.random.uniform(0,1,(3,3))
s=np.diag(np.dot(x,y))
print("dot product=",s)

dot product= [1.02756134 0.67100556 0.79933662]


# 13.How to find the most frequent value in an array?

In [55]:
Z = np.random.randint(0,10,20)
print("most frequent value=",np.bincount(Z).argmax())

most frequent value= 2


# 14.How to get the n largest values of an array

In [54]:
x = np.arange(10000)
np.random.shuffle(x)
n = 5
print("largest values=",x[np.argsort(x)[-n:]])

largest values= [9995 9996 9997 9998 9999]


# 15.How to create a record array from a regular array?

In [52]:
x = np.array([( 2.5, 3),
              ( 3.6, 2)])
y = np.core.records.fromarrays(x.T,names='col1, col2',formats = 'S8, f8')
print(y)

[(b'2.5', 3.) (b'3.6', 2.)]
